### ISSUE TITLE
Notify OOS Button on product list thumb no worky

### ISSUE THREAD

**Issue by fortyhands** [NetoECommerce/Skeletal#103]
Just noticed that line 56 on:
Templates/skeletal/thumbs/product/list.template.html

I don't believe this OOS button works to generate a notify modal box, or to send a user to the product's page.

If this functionality does not work at this time, it would make sense to have the button link to the product page via [@URL@].

Also, on the similar:
Templates/skeletal/thumbs/product/template.html

This button simply takes the user to the product page (where they can sign up for notifications as expected).

**Comment by brandonsheppard** [comment]
Good find @fortyhands & thanks for reporting! We must've missed that template when we changed the functionality.

**Comment by ryvanvel** [comment]
And now it worky again! 0c928a2  

Cheers guys.
