### ISSUE TITLE
No error notification if checking out with voucher without completing required fields

### ISSUE THREAD

**Issue by Redshift-Web-Design** [NetoECommerce/Skeletal#104]
Using latest Skeletal.
Add voucher to cart and proceed to checkout.
If you leave some of the required fields blank and then click 'Confirm & Process' you get a page reload but no Error notifying of missing fields.

Some basic js error checking for blank required fields would be nice to save the reload. Or at least something outputted with cart.error.html like the rest.

**Comment by brandonsheppard** [comment]
I think we should be adding this to the software instead—not ideal to rely on Javascript for this.
