### ISSUE TITLE
'Master Card' should be one word

### ISSUE THREAD

**Issue by ryan0x44** [NetoECommerce/Skeletal#109]
Hi,

I was wondering why the MasterCard pay icon wasn't showing up for us on the checkout page - it's because we have set up MasterCard as a payment method, but the template is checking for Master Card (two words):

`<!--##[%DATA id:'name' if:'like' value:'Master Card'%]##-->`

https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/cart/onepage.template.html#L398

Cheers,
Ryan

**Comment by brandonsheppard** [comment]
Fixed in https://github.com/NetoECommerce/Skeletal/pull/113 — note that we'll be adding a new function that removes the need for static logic like this soon.
