### ISSUE TITLE
Quote Approval not being controlled by config

### ISSUE THREAD

**Issue by Naraceaus** [NetoECommerce/Skeletal#111]
The button here: https://github.com/NetoECommerce/Skeletal/blob/235a49a563030c0a2d7dbf84c0ad2961a6694064/private/www/netosuite/Templates/skeletal/customer/template.html#L35-L41  is only visible when the advanced config ALLOW_QUOTE_APPROVAL is set to Yes.

The button on the same page here: https://github.com/NetoECommerce/Skeletal/blob/235a49a563030c0a2d7dbf84c0ad2961a6694064/private/www/netosuite/Templates/skeletal/customer/template.html#L262 button is not being controlled by the config

**Comment by ryvanvel** [comment]
Fixed in commit #0e6604c
