### ISSUE TITLE
Money Order or Check only to PO address

### ISSUE THREAD

**Issue by curtiswilkinson** [NetoECommerce/Skeletal#116]
Currently in both SysDoc and on the invoice.template.html template, the physical address provided to customers who pay with Money order or check will **only** check the [@CONFIG:COMPANY_POADDR@] config, which is the PO box one. For customers that don't enter an address into that field, no physical address is provided to the people who purchase with these methods.

There would be a lot of places this is the case, but the main two are on the payment success page, and on the invoice:

https://github.com/NetoECommerce/SysDoc/blob/master/printdocs/order/invoice/template.html#L178
https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/cart/invoice.template.html#L104
https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/cart/invoice.template.html#L117

A potential solution is some logic like

```
[%if [@CONFIG:COMPANY_POADDR@]%]
	[@CONFIG:COMPANY_POADDR@]
[%else%]
	[@CONFIG:COMPANY_ADDR@]
[%/if%]
```
However, that runs under the assumption that customers would prioritise checks/money orders being sent to their P.O address over their standard physical address. The ideal solution would probably to have something in the software that indicates what address you'd like the payments to be sent to (probably in the set-up for these payment methods).

**Comment by ryvanvel** [comment]
10/10 recommendation.

I've implemented it on our SysDoc repo with commit 7d57e14.

I've also added the logic to both the skeletal templates in cart, but given our managed checkout release this is more for record keeping purposes so we can suggest the code change to the ecom repo. Which is commit c11ef27, pr #186
