### ISSUE TITLE
Disable autocomplete for buying options forms.

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#119]
For some insane reason, when you refresh a page with a form on, Firefox remembers if any of the form elements were once disabled and re-applies this. This can break the add to cart button if a customer selects a variation product and then refreshes.

Fortunately the solution is simple—just add `autocomplete="off"` to the two relevant forms on the product page ([here](https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/products/includes/buying_options.template.html#L101) and [here](https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/products/template.html#L50)).

```
<form class="buying-options" autocomplete="off">
```

**Comment by ryvanvel** [comment]
Fixed in commit 6356b4c
