### ISSUE TITLE
MasterCard and Diners Club payment icons display parts of the next image

### ISSUE THREAD

**Issue by quatlin** [NetoECommerce/Skeletal#122]
![screen shot 2016-04-26 at 8 23 45 am](https://cloud.githubusercontent.com/assets/4051162/14800886/7256e954-0b88-11e6-93c4-eec7c96c9fbf.png)

To fix:

```
.payment-icon-mastercard {
    background-position: 0px -130px;
}
.payment-icon-diners {
    height: 15px;
}
```

**Comment by ryvanvel** [comment]
Appears to be solved already!
