### ISSUE TITLE
Bank Deposit/Direct Deposit Change

### ISSUE THREAD

**Issue by JulianHolden** [NetoECommerce/Skeletal#130]
In the code, it is currently looking for the name of "Direct Deposit" for the payment method icon to appear in the footer and checkout pages. Many businesses choose to rename this "Bank Deposit" and wonder why it doesn't appear on the front end. 

Location: 

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/footers/template.html#L135-Lundefined
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/footers/checkout.template.html#L66-Lundefined
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/cart/onepage.template.html#L433

Suggested Solution: 

[%if [@name@] like 'Direct Deposit' OR  [@name@] like 'Bank Deposit' %]

**Comment by brandonsheppard** [comment]
Can we update this to use the new function yet? @ryvanvel

**Comment by brandonsheppard** [comment]
Resolved in a recent commit
