### ISSUE TITLE
Minor z-index issue

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#138]
http://skeletaltheme.neto.com.au/sample-product-1

Cart z-index is higher then the popup background.

![screen shot 2016-06-27 at 10 15 47 am](https://cloud.githubusercontent.com/assets/11847839/16365875/2d163018-3c50-11e6-8fef-55fef85f8534.png)

**Comment by ryvanvel** [comment]
Fixed in commit 5aa5e6b to be lower than the lightbox bg but higher than the bootstrap dropdown.
