### ISSUE TITLE
Update tracking code tags to use modern function.

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#140]
We have a better function for loading tracking code without using the confusing function which does not reference a non-existent file.
### Before

```
[%load_template file:"trackingcode/VisitorTracking.html"/%]
```
## After

```
[%tracking_code type:'VisitorTracking'/%]
```
### Before

```
[%load_template file:"trackingcode/RegisterTracking.html"/%]
```
## After

```
[%tracking_code type:'RegisterTracking'/%]
```
### Before

```
[%load_template file:"trackingcode/PurchaseTracking.html"/%]
```
## After

```
[%tracking_code type:'PurchaseTracking'/%]
```
### Before

```
[%load_template file:"trackingcode/Declarations.html"/%]
```
## After

```
[%tracking_code type:'Declarations'/%]
```
## CheckoutTracking

This function actually just needs to be removed:

```
[%load_template file:"trackingcode/CheckoutTracking.html"/%]
```

**Comment by mountainash** [comment]
Will these changes be made to the repo? https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/cart/onepage.template.html still has the 'CheckoutTracking' call.

**Comment by brandonsheppard** [comment]
@mountainash Yep—we'll remove that call and update the rest to use the new tags.

**Comment by mountainash** [comment]
This doesn't actually work?
[%load_template file:"trackingcode/VisitorTracking.html"/%] outputs the scripts from the Neto cPanel as expected.
[%tracking_code type:'VisitorTracking'/%] output nothing... why?

**Comment by brandonsheppard** [comment]
Hey @mountainash—sorry about this. It's `Visitor`, not `VisitorTracking`, my mistake.

[Here's the code](https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/footers/template.html#L185) in the repo.
