### ISSUE TITLE
Contact Us Form via HTTPs

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#145]
When the generic form template is generated in the software it produces the URL of the form page by default:

```
<form action="[%URL type:'page' id:'[@content_id@]'%][%END URL%]" method="post">
```

This doesn't take into account HTTPS addresses and fails when trying to send from a non-https domain.

Proposed solution via a software fix:

```
<form action="[%URL nohost:'1'  type:'page' id:'[@content_id@]'%][%END URL%]" method="post">
```

Tested on my own staging site
https://craigskayakkios.neto.com.au/contact-us

Not something that can be fixed in github but will likely be a recurring issue so I thought I'd post an issue.

**Comment by ryvanvel** [comment]
Did a little investigative work and built a task for a guys in core, CORE-2809.

They'll action that for us sometime this week so moving forward it'll be fixed :)
