### ISSUE TITLE
Instances of "click here to go to x" in btns

### ISSUE THREAD

**Issue by demiscient** [NetoECommerce/Skeletal#147]
First noticed [here](https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/customer/write_review/not_found.template.html) and [here](https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/customer/write_review/template.html).

The buttons are over half a dozen words long and it's causing responsiveness issues in mobiles - the buttons are causing horizontal scroll bars.

Propose changing to:

`<a class="btn btn-success btn-lg" href="[%URL type:'item' id:'[@SKU@]'%][%END URL%]">Go back to [@model@]</a>` 
or
`<a class="btn btn-success btn-lg" href="[%URL type:'item' id:'[@SKU@]'%][%END URL%]">Go back</a>`
and
`<a class="btn btn-default btn-lg"  href="[%URL type:'home'%][%END URL%]">Home</a>`

Other instances I could find of redundant "click here to" wording (where in button form or not) are as follows:

![image](https://cloud.githubusercontent.com/assets/16217544/16681334/6af310a0-4537-11e6-83ed-d79ff3afd5c6.png)

**Comment by brandonsheppard** [comment]
Feel free to submit a pull request for this, @demiscient.
