### ISSUE TITLE
Add new schema tags & fix issues identified with existing schema

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#151]
## General Website:

- [x] [Site Logo](https://developers.google.com/search/docs/data-types/logo)
- [x] [Social Profile Links](https://developers.google.com/search/docs/data-types/social-profile-links)
- [x] [Breadcrumbs](https://developers.google.com/search/docs/data-types/breadcrumbs)
- [ ] [Corporate Contacts](https://developers.google.com/search/docs/data-types/corporate-contacts)

## Product page and thumbnails:

- [x] PriceValidUntil attribute for promotional prices (promo end)
- [x] Product Brand

## [Blog thumbnails and default page](https://developers.google.com/search/docs/data-types/articles)

- [x] Headline
- [x] Author (person schema)
- [x] description
- [x] Fix URL on the thumbnail
- [x] Add publisher (site name)
- [x] date published
- [x] logo

**Comment by curtiswilkinson** [comment]
Unfortunately can't do corporate contacts due to the phone format it requires. 

Needs to always have an internationalised format.

**Comment by curtiswilkinson** [comment]
Finished in https://github.com/NetoECommerce/Skeletal/pull/160
