### ISSUE TITLE
[@unit@] tag on Multilevel Pricing Info - Product Page

### ISSUE THREAD

**Issue by JulianHolden** [NetoECommerce/Skeletal#153]
On the following line: 

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/products/includes/buying_options.template.html#L28

A [@unit@] tag in the table will cause the following with a random number after the price: 

**Buy In Bulk & Save!**
Buy 10 or more:	Pay AU $19.95 1

What is this looking to convey - perhaps "Pay AU $19.95 for 1"? Or is this a bug GitHub Neto lords?

**Comment by curtiswilkinson** [comment]
Good catch Jules, I had a quick look and I believe this should be removed on our side of things

**Comment by brandonsheppard** [comment]
Agreed, should be removed.

**Comment by curtiswilkinson** [comment]
Created pull request found here: https://github.com/NetoECommerce/Skeletal/pull/154
