### ISSUE TITLE
New Mastercard Logo

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#155]
<img width="706" alt="screen shot 2016-07-15 at 9 11 35 am" src="https://cloud.githubusercontent.com/assets/11847839/16858709/2e3a1e94-4a6c-11e6-9e3f-027032fe9c75.png">

**Comment by brandonsheppard** [comment]
Looks like the logo from back in the day: ![](http://design.neto.com.au/assets/uploads/wQlcsmsXtN.png)

**Comment by brandonsheppard** [comment]
This concerns our CDN assets—I've added a task to our internal backlog to update accordingly though.
