### ISSUE TITLE
Common Request for mandatory ABN field

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#161]
Up for discussion, getting a lot of tickets asking for ABN on the wholesale registration form to be set as **required** on the input field.

Quick change, would this be generally acceptable for all customers?

**Comment by mecentric** [comment]
Sounds good in theory. Won't work for international customers though.

**Comment by brandonsheppard** [comment]
This isn't really viable because of internationalisation. Will need to be configurable eventually.
