### ISSUE TITLE
Kits - components pre-selected

### ISSUE THREAD

**Issue by philcon93** [NetoECommerce/Skeletal#184]
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/products/includes/components.template.html#L72

Should this be here? The user can add to cart even without picking a variation and a variation will be pre-selected, i.e the `ref`:

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/products/includes/components.template.html#L84

**Comment by craigblunden** [comment]
Resolved with the following code

Essentially if the customer doesn't select an option from the dropdown the "Current SKU" will automatically be added to cart causing confusion.

The only way around around this would be to disable the add to cart button until a selection has been made which isn't ideal.

Issue raised on #249866

```
[%list_item_variations id:'[@current_sku@]'%]
    [%PARAM *variation_header%]
            <select class="component-var-opt form-control component-config-input" component-id="[@component_count@]" ref="[@specific_id@]">
    [%/PARAM%]
    [%PARAM *variation_body%]
                <option [%if [@^current_sku@] eq [@variation_sku@] %] selected  [%/if%] value="[@value_id@]">[@value_name@] [%IF ![@variation_qty@]%](Out of Stock)[%/IF%]</option>
    [%/PARAM%]
    [%PARAM *variation_footer%]
            </select>
    [%/PARAM%]
[%/list_item_variations%]
```

**Comment by philcon93** [comment]
Possible disable the addtocart button with javascript:

Give each option a `data-stock`:

```
<option value="[@value_id@]" data-stock="[%IF [@variation_qty@]%]1[%else%]0[%/if%]">[@value_name@] [%IF ![@variation_qty@]%](Out of Stock)[%/IF%]</option>
```

Add in javascript similar to the following:

```
var disableatc = false;
$('.component-config-input option').each(function(){
	if($(this).attr('data-stock') == 0){
		disableatc = 1;
	}
});
if(disableatc == 1){
	$('.addtocart').attr('disabled', true);
}
```

**Comment by philcon93** [comment]
Both mine and Craig solution here do not fix this issue as it would create another issue, both to do with kit items with multi specifics.

Craig's option could work on one specific variations, e.g below I'm printing out the current SKU and variation SKU next to each other:

![screen shot 2017-06-13 at 8 47 59 am](https://user-images.githubusercontent.com/13529653/27058648-e3585dc2-5015-11e7-8aa4-817b6fd24385.png)

But when you have multi specifics, the `[@variation_sku@]` will be one of the variations, so specifics will sometimes not match up with the `[@current_sku@]` , resulting in no specific being picked:

![screen shot 2017-06-13 at 8 48 44 am](https://user-images.githubusercontent.com/13529653/27058657-e9a18816-5015-11e7-9c1b-f6f4946d4a42.png)

My option runs into a similar issue here, with one specific variation, `[@variation_qty@]` can pick up the variation qty correctly:

![screen shot 2017-06-13 at 8 55 37 am](https://user-images.githubusercontent.com/13529653/27058707-3b70c742-5016-11e7-8ad3-94fb9b739a25.png)

But when you have multi specifics products, `[@variation_qty@]` will refer to the quantity the specific has in total, e.g the specific option blue has a variation qty of 3:

![screen shot 2017-06-13 at 9 00 21 am](https://user-images.githubusercontent.com/13529653/27058811-ca487226-5016-11e7-8820-1811b22065ac.png)

This is because there are three variations with the specific with a total stock of 3:

![screen shot 2017-06-13 at 9 00 52 am](https://user-images.githubusercontent.com/13529653/27058835-e25a98ee-5016-11e7-8b16-2630e4aee0cd.png)

**Comment by matt-downs** [comment]
Can this be broken up into two separate issues?
1. Kit components should have their variations pre-selected for consistency with regular product page
2. Kit components with out of stock variations shouldn't be able to be added to cart

**Comment by philcon93** [comment]
This issue is being investigated outside of Github.
