### ISSUE TITLE
Editable Kit bug

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#191]
[@fixed_assemble@] returns true when the product is NOT an editable kit.
In codes, it returns true if [@editable_bundle@] is 'n' in database; otherwise, it returns false.

Meaning for all editable kits the input will always be disabled.
`[%if [@fixed_assemble@]%]readonly[%/if%]`

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/products/includes/components.template.html#L40
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/products/includes/components.template.html#L84

**Comment by philcon93** [comment]
I think this has been fixed, unless nostock checkout is enabled, when stock quantity is less than minimum assemble, field changes to unselectable.

Can you check this @craigblunden

**Comment by craigblunden** [comment]
Current understanding of the data tag:

> The [@fixed_assemble@] data tag, which is utilised within the item_kitting function, is intended to return true if the stock quantity of the component is less than it's minimum assemble. We use this to make the quantity field on the front-end read-only when there is not enough stock to satisfy the minimum assemble.

It's currently in testing with the development and will likely be resolved via software updates.

**Comment by philcon93** [comment]
This data tag looks to be working, fixed on v6.9.9
