### ISSUE TITLE
Bootstrap standing order pages

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#209]
There are a number of pages in the [customer directory](https://github.com/NetoECommerce/Skeletal/tree/master/src/templates/customer/standing_orders) which need to be bootstrapped, particularly templates related to standing orders.

To test the standing orders some sample data will need to be set up—document this process so we can repeat easily later.

**Comment by philcon93** [comment]
Completed in #de164f4
