### ISSUE TITLE
Add rel="noopener" to external links

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#212]
[SEO/performance review tools](https://github.com/GoogleChrome/lighthouse/) are rightfully starting to flag this as an issue—we'll need to review the places where anchors are likely to be external and add `rel="noopener"`. [Read more](https://mathiasbynens.github.io/rel-noopener/)

**Comment by philcon93** [comment]
Possible solution:

```
$('a[target="_blank"]').each(function(i){
if($(this).attr('rel') == undefined){
$(this).attr('rel', 'noopener');
}
});
```

**Comment by philcon93** [comment]
Merged into master in September
