### ISSUE TITLE
Variation dropdown selection

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#219]
What determines the `[@selected@]` value? Is it product sort order? 

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/products/template.html#L125

**Comment by brandonsheppard** [comment]
I believe it is simply the first in-stock product in the list. Obviously only applies to sites with preselect_variations enabled.

Also, note that this logic does not dictate _what_ variation is selected (you cannot put in your own custom logic to make whatever you want *selected*)—this logic simply displays the correct `<option>` as selected.
