### ISSUE TITLE
Quoted shipping rates

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#231]
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/cart/includes/cart_items.template.html#L115-L122

What is [@shipping_quote@] and how can we utilise it?

Quote checkout often don't want to provide static quotes for shipping as freight varies. 

Is there a solution available to display POA for quotes shipping totals when specified via the method? 

Feedback from a client:

> I am sure we are not alone in distributing product and not knowing all the weights and measurements. Our products can range from under $5 freight to a couple of hundred just in Australia. So we would love to see a better option that is smoother to use and easier for the end user to understand the process.

**Comment by philcon93** [comment]
That data tag should be true on the following:

shipping_status = 'tba'

**Comment by philcon93** [comment]
This feature was added in v6.10:

https://www.neto.com.au/article/releases/neto-ecommerce/neto-ecommerce-6.10/#a-more-customisable-checkout

It does look like the cart_items.template does have an issue but this has been raised as a bug.
