### ISSUE TITLE
AJAX loading unnecessary scripts after jQuery

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#244]
```
$(document).ready(function(){
    $.ajax("url to your script", {dataType:"script"});
});
```

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/footers/template.html#L180-L182

**Comment by craigblunden** [comment]
https://api.jquery.com/jquery.getscript/

**Comment by Naraceaus** [comment]
I am not sure if you can include custom.js in there, if document ready triggers before the custom.js script loads via ajax then it would affect add to cart or the other stuff that loads in custom.js used for ecom. I could be wrong but it would certainly be something to test (it might of course only occur in situations where customer hits add to cart after document load but before ajax loads custom.js too)

**Comment by brandonsheppard** [comment]
Unfortunately, none of these can be safely lazy loaded or loaded async/deferred due to poor dependency ties all throughout those files.
