### ISSUE TITLE
[%EXTRA_CUSTOMER_FIELDS%] enhancement

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#271]
All form fields have a data tag for `[@required_field@]` which we could use to include front-end validation to avoid extra tweaking. 

On top of that, I should really create an idea for Customer Field Type, wholesale or retail so that they only effect certain forms. 

Such a wanky work around to remove the functionality depending on requirements.

**Comment by philcon93** [comment]
Issue has been fixed and merged in!
