### ISSUE TITLE
Guest checkout doesn't show?

### ISSUE THREAD

**Issue by igor-gp** [NetoECommerce/Skeletal#279]
Hi,

Where guest checkout is enabled, it doesn't actually show up anywhere in the cart/checkout processes. What code would need to be added to make that work?

Thanks

**Comment by philcon93** [comment]
If a customer is logged in then they will have a username, which you could use as logic to display/hide content.

Something like this is done in the Skeletal header:

- https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/headers/template.html#L134
