### ISSUE TITLE
Reviews only show name if posted by noreg customers 

### ISSUE THREAD

**Issue by matt-downs** [NetoECommerce/Skeletal#285]
The tag `[@reviewname@]` is only populated for reviews posted by noreg customers. If a review has been posted by a registered customer it will contain the first and last name in the `[@bill_first_name@]` and `[@bill_last_name@]` tags instead. 

We should change the following logic:
https://github.com/NetoECommerce/Skeletal/blob/1057e6447ce07416ac081d4e8faa72068db7bc86/src/templates/products/template.html#L394-L396
To something like this:
```
[%if [@reviewname@]%]
    By: <span itemprop="author">[@reviewname@]</span> on 
[%elseif [@bill_first_name@]%]
    By: <span itemprop="author">[@bill_first_name@]</span> on 
[%/if%]
```

**Comment by philcon93** [comment]
@matt-downs do you have a working example of this? or does this change all reviews with no `reviewnames` to the current customer logged in?

**Comment by matt-downs** [comment]
@philcon93 check out the reviews tab on these two themes.
Default:
https://matts-surfboard.staging-aws.neto.net.au/sample-americana-dining-chair?nview=skeletal
Patch:
https://matts-surfboard.staging-aws.neto.net.au/sample-americana-dining-chair?nview=skeletal-patch

**Comment by matt-downs** [comment]
It seems like the `[@reviewname@]` tag is only populated via the `customername` input field, which is hidden from logged in users:
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/customer/write_review/write.template.html#L41-L50

Not sure whether this is better fixed on the backend though.
