### ISSUE TITLE
invoice.template.html missing closing div

### ISSUE THREAD

**Issue by matt-downs** [NetoECommerce/Skeletal#287]
## Problem
The invoice.template.html is missing a closing div statement which causes the `.wrapper-footer` div to render within the `#main-content` div. On all other pages `.wrapper-footer` sits directly below `#main-content`.

This error causes the footer to align slightly further to the right than the other pages. More noticeably, if the site has a background colour set on the `.wrapper-footer` element it will only span the width of the `#main-content` element, not the full width of the page like everywhere else on the site. 

### `.wrapper-footer` element on invoice.template.html:
![](http://i.imgur.com/7WMgq9D.png)
### `.wrapper-footer` element on cart page:
![](http://i.imgur.com/zoKyI4q.png)

## Solution
A `</div>` needs to be added to the bottom of this file:
https://github.com/NetoECommerce/Skeletal/blob/1057e6447ce07416ac081d4e8faa72068db7bc86/src/templates/cart/invoice.template.html#L289

### `.wrapper-footer` element on invoice.template.html after changes:
![](http://i.imgur.com/Qoc24PX.png)

**Comment by philcon93** [comment]
This div.row needs a closing div 
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/cart/invoice.template.html#L21

**Comment by philcon93** [comment]
Merged into master September
