### ISSUE TITLE
Spike - using netothemeinfo.txt

### ISSUE THREAD

**Issue by philcon93** [NetoECommerce/Skeletal#323]
All themes have a netothemeinfo.txt file which is meant to be used for the information displaying on the theme store. I'm pretty sure this doesn't occur anymore since i've been updating the theme store for the past year and updating theme information happens a different way.

Because of this, I think it would be a good idea to use the themes netothemeinfo.txt to add in more information about the theme and where to get help if needed. Information that would be useful:

- Version number - Updates every time the theme is updated on the theme store,
- Theme Developer - name of individual/company that created theme,
- Theme documentation - Link to themes documentation,
- Theme support - email/link to relevant developer for additional assistance.

Would any other information be useful? Should this stay as txt or converted into a json file? Should the compile script have an additional step to update the netothemeinfo.txt from the themes package.json?

**Comment by matt-downs** [comment]
JSON could be cool! Otherwise if we still wanted to include a human readable description of the theme, we could use a markdown doc with some specific YAML metadata at the top. Eg: https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents

**Comment by philcon93** [comment]
Or use package.json for this purpose, it can include all the fields needed, plus it would even allow a user to use node for a Neto site (they would have to download the whole theme and do npm install). 

The compile script would have to be updated and im not sure if this would mess anything up when a user installs a new theme.

**Comment by philcon93** [comment]
Apparently, package.json can have custom key/values, I think it might be good to have a 'theme_names' value which takes an array of the theme names. 

This would replace having a netothemeinfo.txt file which I'm confused when it gets added to a theme, see theme start kit issue:

- https://github.com/philcon93/Theme-Starter-Kit/issues/3

The new compile script would loop through that array to make the theme zips.

**Comment by philcon93** [comment]
@matt-downs we have free themes that are the same repo but with different stylesheets. The compile script takes this netothemeinfo.txt into account when compiling up the themes.

- https://github.com/NetoECommerce/Midsummer-Theme/tree/master/src/templates

**Comment by matt-downs** [comment]
Ohhh I did not know this...

Going off your idea, we could have a key `neto-theme-info` in `package.json` that could accept a single object or an array - making these both valid:
```
{
    ...
    "neto-theme-info": {
        "name": "Skeletal",
        "description": "blah blah blah blah"
    }
}
```
```
{
    ...
    "neto-theme-info": [
        {
            "name": "Skeletal",
            "description": "blah blah blah blah"
        },
        {
            "name": "Muscle",
            "description": "blah blah blah blah"
        }
    ]
}
```
