### ISSUE TITLE
Update Skeletal to Font Awesome 5

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#328]
Details in Confluence in DES space. 

Header CDN replace with Neto CDN package? 
https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/headers/template.html#L20

**Comment by philcon93** [comment]
This would be a rather large project to undertake which isn't really possible unless we also update neto.js, as it uses FA4 class names. FA5 doesn't use the same class names:

- https://fontawesome.com/how-to-use/web-fonts-with-css#basic-use

I'm a little unsure of using the pro service on Skeletal. Would that mean anyone developing a theme could use FA5? Is that allowed under the FA license?

**Comment by craigblunden** [comment]
> This would be a rather large project to undertake which isn't really possible unless we also update neto.js, as it uses FA4 class names. FA5 doesn't use the same class names:

Do you have an example? I couldn't find any. 

> Would that mean anyone developing a theme could use FA5? Is that allowed under the FA license?

Correct. :) 

It's a perpetual license, for any user to use on multiple sites.

**Comment by craigblunden** [comment]
I didn't consider app.css at the time, but there are only a few references which are manageable.

**Comment by craigblunden** [comment]
**Performance concern**
You can choose between the different styles and not include them all.
FA4 All icons 39kb

FA5 CSS File Comparisons without gzip or caching:
All icons - 41kb
Solid - 600b
regular - 656b
light - 596b

Web fonts are comparable. 

As it stands, all fonts on themes would be considered 'solid' so we could potentially lower site bandwidth by 40kb and use new icons for premium/bespoke design packages. 

This also allows for a much faster upgrade path.

**Comment by craigblunden** [comment]
<link href="https://use.fontawesome.com/releases/v5.0.6/css/fontawesome.css" rel="stylesheet">
<link href="https://use.fontawesome.com/releases/v5.0.6/css/brands.css" rel="stylesheet">
<link href="https://use.fontawesome.com/releases/v5.0.6/css/regular.css" rel="stylesheet">
<link href="https://use.fontawesome.com/releases/v5.0.6/css/solid.css" rel="stylesheet">

**Comment by craigblunden** [comment]
```
<script defer src="https://use.fontawesome.com/releases/v5.0.3/js/all.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.3/js/v4-shims.js"></script>
```

Not ideal, but possible upgrade path. 

```
Our v4 shim allows you to keep your old version 4 icon names, aliases, and syntax, and we’ll even upgrade you from FA4’s web fonts to FA5’s new SVG with JavaScript implementation.

To use it, you’ll want to remove your version 4 files and references, then add the SVG with JavaScript files and version 4 shim to your <head>.
```

all.js full size is **668** KB which is injected async so shouldn't affect performance but overall size is a bit lame.
