### ISSUE TITLE
Register forms reset all custom field values when page is reloaded on validation error

### ISSUE THREAD

**Issue by matt-downs** [NetoECommerce/Skeletal#333]
Register and wholesaleregister forms reset all custom field values when page is reloaded on validation error - eg. if you mistype your password you will have to fill out all of the custom fields again. 

Here is an example field from our current template:
`<input type="text" class="form-control" id="[@field_id@]" name="[@field_id@]" value="[%NOHTML%][@field_default@][%END NOHTML%]" [%if [@required_field@]%]required="true"[%/if%]>`

To restore the values previously entered, we can probably add in something like this:
```html
[%set [@pre_entered@] %][%form id:'[@field_id@]'/%][%/set%]
...
value="[%nohtml%]
[%if [@pre_entered@]%][@pre_entered@][%else%][@field_default@][%/if%]
[%nohtml%]"
```
The issue is that we still want the field to get it's initial value from the `[@field_default@]` tag, so we need to check if the `[%form id:'[@field_id@]'/%]` actually contains data before populating the `value` attribute. 

Is there a more elegant solution than setting a variable?

**Comment by philcon93** [comment]
This issue is being investigated outside of Github.
