### ISSUE TITLE
Colour Swatch needed

### ISSUE THREAD

**Issue by AndyLIUMel** [NetoECommerce/Skeletal#344]
Do we need to add this colour swatch so that
colour variations in the form of coloured square swatches, giving people a visual breakdown of the hues on offer?

**Comment by matt-downs** [comment]
Hi @AndyLIUMel, we have a tweak doc to add functionality here:
https://developers.neto.com.au/documentation/web-designers/tweak-documents/product-page/colour-variation-swatches/

It's probably something that's best implemented in a custom theme rather than Skeletal, but that's just my opinion. 😄
