### ISSUE TITLE
Remove images from default.template

### ISSUE THREAD

**Issue by bloycey** [NetoECommerce/Skeletal#348]
Can we please remove the following from the default cms template? I find myself removing it for customers all the time. It often overlaps blog content and just floats awkwardly over to the side. 

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/cms/default.template.html#L27-L28

```
<img src="[%asset_url type:'content' id:'[@content_id@]' default:'[@config:imageurl@]/pixel.gif'/%]" class="pull-right" alt="[@name@] main image"/>
<img src="[%asset_url type:'content' thumb:'alt_1' id:'[@content_id@]' default:'[@config:imageurl@]/pixel.gif'/%]"  class="pull-right" alt="[@name@] image"/>
```

**Comment by quatlin** [comment]
We should replace that class with `img-responsive`

**Comment by philcon93** [comment]
This issue is being investigated outside of Github.
