### ISSUE TITLE
Optimise Config Tags

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#373]
Do not use [$cgiurl$] or [@config:cgiurl@] - use [@config:cgi_url@] instead!
Do not use [$company$] or [@config:company@] - use [@config:COMPANY_NAME@] instead!
Do not use [$credit_account$] or [@config:credit_account@] - use [@config:CREDIT_ACCNAME@] instead!
Do not use [$MONEYSIGN$] or [@config:MONEYSIGN@] - use [@config:currency_symbol@] instead!
Do not use [$homeurl$] or [@config:homeurl@] - use [@config:home_url@] instead!
Do not use [$captchaimageurl$] or [@config:captchaimageurl@] - use [@config:REL_CAPTCHAIMAGE_URL@] instead!
Do not use [$imageurl$] or [@config:imageurl@] - use [@config:REL_IMAGES_URL@] instead!
Do not use [$image_url$] or [@config:image_url@] - use [@config:REL_IMAGES_URL@] instead!
Do not use [$themeurl$] or [@config:themeurl@] - use [@config:REL_THEME_URL@] instead!
Do not use [$securecgiurl$] or [@config:securecgiurl@] - use [@config:secure_cgi_url@] instead!
Do not use [$idleminutes$] or [@config:idleminutes@] - use [@config:sessionTimeout@] instead!

The preferred tags are better optimised and will have a performance benefit. 

Ben H also found if you use [@config:asdf@] (ie an "unknown" config tag) it will create additional performance deficits.

**Comment by philcon93** [comment]
This issue is being investigated outside of Github.
