### ISSUE TITLE
Have product thumbnails only display "From" text if child prices differ from one another

### ISSUE THREAD

**Issue by demiscient** [NetoECommerce/Skeletal#377]
There should not be "From" text on the price of every product that happens to have variations in colours or (clothing) sizes _if all of the child prices are the same_. For example, a small, medium, and large coffee, which would have different prices for each, should logically have a "From" in front of the thumbnail (parent) price. A small, medium, and large t-shirt, would likely not have different prices, so the "From" label in front of the price is moot. It would be appropriate to implement code that deals with both sorts of scenarios.

**Comment by matt-downs** [comment]
#372

Blocked by a “bug” at this stage
