### ISSUE TITLE
Unable to enter billing city/state when country != AU

### ISSUE THREAD

**Issue by matt-downs** [NetoECommerce/Skeletal#381]
Fields for city and state on the `_myacct/edit_account` page are not visible when another country is selected:
![chrome_2018-04-04_09-30-29](https://user-images.githubusercontent.com/6867163/38280904-3aa3c004-37eb-11e8-97f6-ead4d6dfc904.png)

**Comment by markjaniczak** [comment]
#368 

Related, no?

**Comment by matt-downs** [comment]
@markjaniczak looks pretty similar? Different template though. 

Does the code changed in #368 fix this issue (if applied to the `templates/customer/edit_account/template.html` template)?

**Comment by matt-downs** [comment]
Example fix: [template.zip](https://github.com/NetoECommerce/Skeletal/files/1888092/template.zip)

This doesn't check anything against the installed suburbs though - it will simply make the text visible and editable if the country != AU
