### ISSUE TITLE
voucher.template - Incorrect HTML

### ISSUE THREAD

**Issue by GerryFort** [NetoECommerce/Skeletal#389]
Line 216 has `</div>` missing - therefore if you have more than 5 vouchers in your cart the whole template breaks down. Adding `</div>` to line 216 fixes this issue.

**Comment by philcon93** [comment]
I believe https://github.com/NetoECommerce/Skeletal/pull/319 addresses this issue. Just waiting on @dalerodgie to update his PR then we can review it again :)

**Comment by GerryFort** [comment]
Thanks @philcon93 !
