### ISSUE TITLE
warranty/dispute_updated - Incorrect HTML

### ISSUE THREAD

**Issue by GerryFort** [NetoECommerce/Skeletal#392]
Line 11;
`<input type="button" class="btn btn-default"> value="Done" onClick="window.location.replace('[%URL page:account type:warranty id:[@dispute_id@]%][%END URL%]');">`

Change to;
`<input type="button" class="btn btn-default" value="Done" onClick="window.location.replace('[%URL page:account type:warranty id:[@dispute_id@]%][%END URL%]');">`

There is an unnecessary **>** after _class="btn btn-default"_

EDIT: Worked out how to create PR's so have done so; https://github.com/NetoECommerce/Skeletal/pull/393

**Comment by philcon93** [comment]
#393 merged in 👍
