### ISSUE TITLE
Addtocart - button Animation Issue

### ISSUE THREAD

**Issue by GerryFort** [NetoECommerce/Skeletal#395]
Hi there,

I've noticed an error with the ADD TO CART button on items with variations. When you press the ADD TO CART button; the button itself does not animate.

For an example;
http://skeletaltheme.neto.com.au/sample-product-1
Change the option to GREEN then press ADD TO CART.

On the initial selected product, the button animation works - but once you make a change the animation stops working.

I spoke with Dale from Neto who tweaked the code a little, however it still doesn't seem to work; the code he provided was;
```
$(".btn-loads").on("click", function(){
    $(this).button("loading");
    var pendingbutton=this;
    setTimeout(function(){
        $(pendingbutton).button("reset");
    },3000);
});
```
Which is a slight modification of the current code in **custom.js**. Any further assistance will be greatly appreciated as Dale is on Holiday now.

Kind Regards,
Gerry

**Comment by philcon93** [comment]
Merged in
