### ISSUE TITLE
Parts of system broken when email address contains + character

### ISSUE THREAD

**Issue by matt-downs** [NetoECommerce/Skeletal#397]
The following parts of the system break when the `[@email@]` contains a `+` char - it needs to be properly URL encoded. Maybe use the `[%encodeuri%]` func. 

https://github.com/NetoECommerce/Skeletal/blob/a3aa7a048ab73b8ee5410097095cb7ca1bb8b642/src/templates/cart/invoice.template.html#L28
https://github.com/NetoECommerce/Skeletal/blob/7fbca3f070d42eca8f50bf53baf04f4fd42387cd/src/templates/cart/rental_invoice.template.html#L23
https://github.com/NetoECommerce/Skeletal/blob/ed380ac72370376b4e145f2ff4734d61a0bf6839/src/templates/customer/approve_quote/accept_quote_confirm.template.html#L16
https://github.com/NetoECommerce/Skeletal/blob/a0e4f52d228dcdbd8490fe41207577db7b062202/src/templates/customer/approve_quote/template.html#L43
https://github.com/NetoECommerce/Skeletal/blob/a0e4f52d228dcdbd8490fe41207577db7b062202/src/templates/customer/approve_quote/template.html#L46

**Comment by philcon93** [comment]
Merged in
