### ISSUE TITLE
og image issue on product template

### ISSUE THREAD

**Issue by kiel-abraham** [NetoECommerce/Skeletal#399]
og image using [@full_image@] tag. Isn't rendering. Needs asset URL or just to be removed as there is one in the header

https://github.com/NetoECommerce/Skeletal/blob/e4ed8fd3a8278b96e13cbdd509b384735cb73d1a/src/templates/products/includes/images.template.html#L1

**Comment by brandonsheppard** [comment]
Not sure—maybe check the PR's Curtis did a while back when he updated this stuff.

**Comment by philcon93** [comment]
I think he missed removing this, it has been there since the restructure;

- https://github.com/NetoECommerce/Skeletal/commits/master/src/templates/products/includes/images.template.html

**Comment by philcon93** [comment]
Merged in :)
