### ISSUE TITLE
surcharge_total not shown on cart page 

### ISSUE THREAD

**Issue by matt-downs** [NetoECommerce/Skeletal#400]
# Issue
![802](https://user-images.githubusercontent.com/6867163/39508023-17f29360-4e24-11e8-8f02-0e871231047d.png)

# Solution
Add the following row to the cart breakdown table
https://github.com/NetoECommerce/Skeletal/blob/e4ed8fd3a8278b96e13cbdd509b384735cb73d1a/src/templates/cart/includes/cart_items.template.html#L129-L133

**Comment by philcon93** [comment]
Merged in
