### ISSUE TITLE
Facebook og tags in head are too broad.

### ISSUE THREAD

**Issue by bloycey** [NetoECommerce/Skeletal#416]
Needs a little more research before creating a PR however it seems like by default our og type is always set to 'website'.

https://github.com/NetoECommerce/Skeletal/blob/master/src/templates/headers/includes/head.template.html#L8

This isn't ideal as there are more suitable types that may deliver better social media thumbnails. For instance [product](https://developers.facebook.com/docs/reference/opengraph/object-type/product/) and [article](https://developers.facebook.com/docs/reference/opengraph/object-type/article/)

I think these are the main types that we would use. Maybe the new og tag could look something like this:

`<meta property="og:type" content="[%if [@config:current_page_type@] eq 'product'%]product[%else%]article[%/if%]"/>`

**Comment by philcon93** [comment]
Useful links:

- Debugger - https://developers.facebook.com/tools/debug/
- Product type - https://developers.facebook.com/docs/reference/opengraph/object-type/product/

Also if your keen we could expand our meta tags to include twitter cards, 

- https://www.goinflow.com/social-markup-for-ecommerce-sites/

**Comment by philcon93** [comment]
This issue is being investigated outside of Github.
