### ISSUE TITLE
Clear Price Filter not working

### ISSUE THREAD

**Issue by NetoSupport** [NetoECommerce/Skeletal#44]
**Steps to replciate**

1. http://dev-brandon.neto.com.au/category-two/sub-category-four/
2. Change Price Filter
3. Clear Price Filter

Clearing the Price filter reloads the page but nothing changes.

**Comment by brandonsheppard** [comment]
Front-end code is [correct](https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/cms/includes/sidebar.template.html#L142) so this must be a software thing.
