### ISSUE TITLE
Setup proper support for autofill

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#51]
Autofill is great, especially for mobile checkout. See all details [here](http://updates.html5rocks.com/2015/06/checkout-faster-with-Autofill).

The credit card stuff in Chrome is awesome:

![](http://design.neto.com.au/assets/uploads/Xour4JISRi.png)

@Redshift-Web-Design will dig this.

**Comment by Redshift-Web-Design** [comment]
Redshift-Web-Design is digging the shit out of this. Love it :+1:

**Comment by Redshift-Web-Design** [comment]
Recon it's worth launching the CC Expiry selects for inputs to utilise autofill?

**Comment by brandonsheppard** [comment]
@Redshift-Web-Design not sure what you mean?

Note we should wait until the new checkout module is complete before we look into this one too much.

**Comment by brandonsheppard** [comment]
This doesn't seem to actually invoke that CC feature in Chrome anymore so maybe it's a dud. Will reinvestigate later I guess!
