### ISSUE TITLE
fancybox_loading.gif is absent from location on cdn.neto

### ISSUE THREAD

**Issue by curtiswilkinson** [NetoECommerce/Skeletal#65]
Sites are calling the fancybox_loading.gif file from the following location: https://cdn.neto.com.au/assets/neto-cdn/fancybox/2.1.5/fancybox_loading.gif

This is a file-name that is there, but the actual .gif file is not present. As such, the loader is just not appearing during fancybox load. 
![loaderfailed](https://cloud.githubusercontent.com/assets/12440573/9159722/5a7f0246-3f71-11e5-86e1-dc814a3d3b8b.png)

**Comment by brandonsheppard** [comment]
This should be fixed now @Redshift-Web-Design

**Comment by Redshift-Web-Design** [comment]
Rad. Thanks guys.
