### ISSUE TITLE
onepage.template.html > login.template.html

### ISSUE THREAD

**Issue by Redshift-Web-Design** [NetoECommerce/Skeletal#66]
Just a quick one... This page could really, really do with a tab index set and a submit button or some jquery to click submit on ENTER. So people like myself who tend to use Tab and Enter when submitting forms, don't think that something is broken.

**Comment by brandonsheppard** [comment]
I agree!

**Comment by brandonsheppard** [comment]
Hey Dude,

What form are you referring to specifically for this one? I assumed you meant the [checkout](https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/cart/onepage.template.html) and the [login](https://github.com/NetoECommerce/Skeletal/blob/master/private/www/netosuite/Templates/skeletal/customer/register/template.html) templates but both seem to work fine with tabbing for me...

**Comment by brandonsheppard** [comment]
@ryvanvel Can you investigate this one? Looks like the issue is mostly relevant to the submit button functionality.

**Comment by ryvanvel** [comment]
Tested in triple, seems to be fine in all enter/tab cases. If you can provide extra information to help us recreate your issues I'll take another look, until then, Skeletal appears to work just fine for tabbing & enter on both the cart and the checkout.
