### ISSUE TITLE
Support for Enhanced eCommerce - Google Analytics

### ISSUE THREAD

**Issue by jesse-neto** [NetoECommerce/Skeletal#73]
Please add support to Skeletal for Enhanced eCommerce - Google Analytics:

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce

**Comment by Redshift-Web-Design** [comment]
Yess… Please do. This has been in my backlog for ages.

 

--

**Comment by brandonsheppard** [comment]
This looks like it'd actually require to be built on the software side, not the template side. Would be so messy to generate this stuff with the parser.

Have you prototyped this at all @Redshift-Web-Design ?

**Comment by Redshift-Web-Design** [comment]
Nah I skimmed the kilometer long docs and the more I scrolled the deeper this project got buried in my backlog. Looks a bit gnarly but the benefits look worth it. Will have another look when I get a sec.

**Comment by philcon93** [comment]
We have been looking into Enhanced eCommerce, as said previously though, this wouldn't be theme specific though, we would want to do it via the software possible third party scripts like the current Google Tracking Analytics.
