### ISSUE TITLE
Default template parse tag

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#74]
Skeletal/private/www/netosuite/Templates/skeletal/cms/default.template.html

Need to wrap the content descriptions within **Parse** tags. Causing broken contact forms.

```
[%parse%]
	[@content_description1@]
	[@content_description2@]
	[@content_description3@]
    [%/ parse%]
```

**Comment by brandonsheppard** [comment]
41d8dd6d0fe80083d1328bc2035f9f4878260ae8
