### ISSUE TITLE
Wishlist .npopup

### ISSUE THREAD

**Issue by Redshift-Web-Design** [NetoECommerce/Skeletal#75]
Seems to have the close button hidden in app.less/css on xs viewport and no other obvious way to close the modal. I think it needs a restyle like the Notify Modal.

**Comment by Redshift-Web-Design** [comment]
FYI: For now I have set .npopup width to 90% on xs and removed display:none; on .npopup-btn-close. Seems to work ok.

**Comment by brandonsheppard** [comment]
Fixed here: 8ac0ece52f81390ad0fc92e2bfc9af42948f6c03

> **@Redshift-Web-Design:**
> I  think it needs a restyle like the Notify Modal.

Absolutely—we plan to template these popups out of `neto.js` so people can use whatever popup plugin they want.
