### ISSUE TITLE
Shopping Cart Page Shipping Styling

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#76]
When calculating the shipping the options for delivery have button styles so if you overwrite the standard .btn colours the background is all messed up.
![screen shot 2015-09-07 at 18 39 33](https://cloud.githubusercontent.com/assets/11847839/9712702/ce9a9a9e-558f-11e5-824c-b1b5133e0f87.png)

Solution:
Remove the btn class styles from the Shipping Method function:

```
<label class="btn btn-block btn-default text-left" for="[@id@]">
```

**Comment by brandonsheppard** [comment]
76cf9bbbfb4ffab843f73cccf01a52cde3f39c3e
