### ISSUE TITLE
Bug passing info from cart to checkout

### ISSUE THREAD

**Issue by Redshift-Web-Design** [NetoECommerce/Skeletal#78]
It seems that info entered into cart is not being passed to checkout page. This means that a postcode entered into the shipping calculator is not passed and it also seems that whatever logic is being used to decide which radio is checked (snippet from onepage.template below) is also not working, causing it to default to 'A different address' which is gross.

```
<div class="radio">
	<label>
		<input name="ship_mode" value="b" type="radio" [%DATA id:'ship_mode' if:'eq' value:'b'%]checked[%END DATA%]/>
		My billing address
	</label>
</div>
<div class="radio">
	<label >
		<input name="ship_mode" value="s" type="radio" [%DATA id:'ship_mode' if:'eq' value:'s'%]checked[%END DATA%]/>
		A different address
	</label>
</div>
```

**Comment by brandonsheppard** [comment]
Determined to be software related and not front-end.
