### ISSUE TITLE
Broken Authority to Leave login on Cart page

### ISSUE THREAD

**Issue by curtiswilkinson** [NetoECommerce/Skeletal#81]
On the /cart/includes/shipping_options.template.html template, an outdated config tag is used for show/hide on the Authority to Leave section.

Logic is currently:
[%if ![@hide_authority_to_leave@]%]

and needs to be updated to:
[%if ![@config:hide_authority_to_leave@]%]

**Comment by brandonsheppard** [comment]
Behold!

54f64627cb86a0e67961f86b965f5c345415da19
