### ISSUE TITLE
Missing icons on mobile menu for iPhone 5

### ISSUE THREAD

**Issue by dalerodgie** [NetoECommerce/Skeletal#83]
When displaying the theme on the iPhone 5 or 5s only the **Menu** icon displays:

![iphone5](https://cloud.githubusercontent.com/assets/7511456/10179853/38e469de-674c-11e5-85ef-089c5b6f31ca.jpg)

This is the CSS that is causing the issue in the app.css file:
~~~
@media (max-width: 335px) {
  .nMobileNav > li {
    display: none;
  }
  .nMobileNav > li:first-child {
    display: block;
    width: 100%;
  }
}
~~~

It works fine in the iPhone 6s (larger screen).

Also affected:

http://classictheme.neto.com.au/
http://countrytheme.neto.com.au/
http://ardrossantheme.neto.com.au/
http://sherwoodtheme.neto.com.au/
http://rightsidetheme.neto.com.au/
http://vintagetheme.neto.com.au/
http://byrontheme.neto.com.au/
http://ascottheme.neto.com.au/
http://westendtheme.neto.com.au/
http://cartbrewerytheme.neto.com.au/
...there may be more

**Comment by dalerodgie** [comment]
This is the patch I have used to fix the issue:

~~~
@media (max-width: 335px) {
  .nMobileNav > li {
    display: inline-block;
  }
  .nMobileNav > li:first-child {
    display: inline-block;
    width: 23%;
  }
}
~~~

It is added in the style.css file.

**Comment by brandonsheppard** [comment]
Already fixed here: https://github.com/NetoECommerce/Skeletal/commit/6518a575af3b86be05f9caf3bad6692c209f650a
