### ISSUE TITLE
Update invoice confirmation message to use PAYMENT_CONFIRMATION tag

### ISSUE THREAD

**Issue by jeff-stamborski** [NetoECommerce/Skeletal#85]
A new PAYMENT_CONFIRMATION tag has been added, and we can use it to make the order confirmation message to be more dynamic and informative.

File:
Skeletal/private/www/netosuite/Templates/skeletal/cart/invoice.template.html

Change from:
`<div class="alert alert-success">Congratulations - Your Order Has Been Confirmed!</div> `

To:
```html
    [%PAYMENT_CONFIRMATION%]
    [%PARAM *header%]
    [%/PARAM%]

    [%PARAM *body%]
    [%IF [@type@] eq 'success' %]
    <div class="alert alert-success">[@message@]</div>
    [%ELSEIF [@type@] eq 'warning'%]
    <div class="alert alert-warning" role="alert">[@message@]</div>
    [%ELSEIF [@type@] eq 'error'%]
    <div class="alert alert-warning" role="alert">[@message@]</div>
    [%/IF%]
    [%/PARAM%]

    [%PARAM *footer%]
    [%/PARAM%]

    [%/PAYMENT_CONFIRMATION%]
```

**Comment by brandonsheppard** [comment]
Complete in 7cfbc5cbfe751a7c862fae73f400be4d87f0643d
