### ISSUE TITLE
Payment Icon classes are incorrect (swapped around)

### ISSUE THREAD

**Issue by curtiswilkinson** [NetoECommerce/Skeletal#87]
This issue is that the classes payment-icon-discover and payment-icon-diners have incorrect CSS that has their image background position wrong.
![screen_shot_2015-11-10_at_10 58 10_am_1024](https://cloud.githubusercontent.com/assets/12440573/11051349/223bae40-879a-11e5-9316-d3e8a3559e03.png)

For example, the class payment-icon-discover will give the "diners" image incorrectly and vice versa. 

This appears to be affecting multiple themes and affects both the checkout page AND the footer payment icons. (Customer originally had the issue on byron).

**Comment by ryvanvel** [comment]
Updated & committed : 64d4ef2
