### ISSUE TITLE
Carousel thumbnail should include a CTA

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#88]
![unnamed-1](https://cloud.githubusercontent.com/assets/5397325/11133389/57b1ffb8-89e1-11e5-96d1-9a47f42dda0f.png)
![unnamed](https://cloud.githubusercontent.com/assets/5397325/11133394/5a048f92-89e1-11e5-9614-53ee4d79e5f3.png)

**Comment by ryvanvel** [comment]
Done & submitted - 81e13a2
