### ISSUE TITLE
Preferred payment methods doesn't have the ignore_balance:'1' param

### ISSUE THREAD

**Issue by curtiswilkinson** [NetoECommerce/Skeletal#89]
On the /private/www/netosuite/Templates/skeletal/customer/edit_account/template.html

There is a [%payment_methods%] function; this generates a dropdown box from available payment methods.
The problem arises when there are minimums applied to the payment methods and a customer hasn't had a checkout yet. This dropdown shows as blank because the payment methods aren't being detected as available due to the lack of an order minimum.

This can be rectified with the ignore_balance:'1' param being placed on the function.

**Comment by ryvanvel** [comment]
Fixed & comitted with f100a7b
