### ISSUE TITLE
Shipping method displaying as white due to label class

### ISSUE THREAD

**Issue by curtiswilkinson** [NetoECommerce/Skeletal#92]
File path: Skeletal/private/www/netosuite/Templates/skeletal/customer/track_order/order.template.html

On the track order page, the shipping method is displaying in white on all themes due to app.css having the .label class text colour as #ffffff
![whitetextlabel](https://cloud.githubusercontent.com/assets/12440573/11519377/7a67bb98-98e5-11e5-8454-f4ecafb64b8b.png)

This is due to the following code on the above template:
<span class="label">[@ship_method@]</span>

I suggest simply removing the .label class and having it display as normal text like this:
![removedlabelclass](https://cloud.githubusercontent.com/assets/12440573/11519410/accbea8c-98e5-11e5-96c0-ee32b6383232.png)

**Comment by ryvanvel** [comment]
Fixed & comitted with f100a7b
