### ISSUE TITLE
Sort order for Product Filters

### ISSUE THREAD

**Issue by dalerodgie** [NetoECommerce/Skeletal#94]
Can we add a sort order for the variation product filters. Change `cms/includes/sidebar.template.html` in line 10 from:

~~~
[%PRODUCT_FILTER type:'variations' autohide:'0'%]
~~~

to

~~~
[%PRODUCT_FILTER type:'variations' autohide:'0' sortoption:'sortorder'%]
~~~

This will sort the specifics names by the sort order set in the control panel:

![product specifics](https://cloud.githubusercontent.com/assets/7511456/11577842/831621d4-9a6c-11e5-9b35-3faa58a7eb66.jpeg)

Adding `sortoption:'sortorder'` will make it easier for customers to arrange the specifics in the sidebar.

**Comment by ryvanvel** [comment]
Fixed & comitted with f100a7b
